---
title: "Wrapup 1: Introduction to statistics and data exploration"   
output:
    html_document:
      code_download: true    
      theme: cosmo
      toc: true
      toc_float: true
      highlight: tango
      number_sections: true
---

# Importance of Statistics for empirical research?
- Experimental design
- Data exploration
- Statistical inference

## Concepts on experimental design?
- Defining Population
- Importance of Randomisation
- Sample size
- Control: simultaneous, randomizing, blinding
- Confounding: in which studies do you have a higher risk in confounding?


## Basic Concepts
- Types of variables
- Random variables
- Probability theory
- Statistical modeling
- Estimation
- Why are all our statistics/estimators random variables
- No assumptions: empirical vs assumptions

Data exploration
-

# Questions

---

## How confident are you in recognizing different types of variables in a study

---
---

## How confident are you in understanding the importance of randomization?

---
---

## How confident are you in understanding how data, statistics and conclusions change from sample to sample and what the impact is of sample size on the uncertainty.

---
---

## How confident are you in explaining somebody the importance of data exploration and the importance of showing the data as raw as possible

---
---

## How confident are you in spotting data that deviates from the normal distribution

---
